---
git:
  user: "Kuba Kanclerz"
  email: "kanclerj@uek.krakow.pl"
repository_url: https://bitbucket.org/jkanclerz/ani-creator.git
os_packages:
  - python36
  - python36-pip
  - git
  - tree
  - mc
bucket_name: "kkanclerz-zid"
python_dependencies:
  - boto3
  - pytest
  - flask
app_root_dir: "~/ani-creator"
